### ISSUE TITLE
.sig header readout of the notes?

### ISSUE THREAD

**Issue by Frederik-D-Weber** [KubaRad/sleeppy#2]
Thanks for the code base to help convert Schwarzer Brainlab . sig files to edf, wich I here streamlined a little more:
https://github.com/Frederik-D-Weber/sigtoedf

Your code was of great help and thanks to it we could recover event information from the .sig files and header info that were otherwise lost. However, we desparately also need to decode the NOTES information within the header info of the sig files for which no template (also code) seems to exist. I tried similar structure as the EVENT decoding, but it did not match. 
I have the pointers to the data section containing the NOTES info, but do not know the decoding template to extract it.

Could you help us to decode that part or shed some light on how you know the data format of the other parsed parts? That would be much appreciated.

Freddy

**Comment by KubaRad** [comment]
Hi, sorry for the late answer but it is a pretty hectic time...

The code related to Brainlab files is old - we have stopped using our Schwarzer device in 2012 and rarely need the data acquired in that device. I've never tried to extract the notes and it is impossible for me to get some  test data. But we have a description of Brainlab files - please contact me directly (kuba@radlinski.eu).

Kuba
